server:
  port: 8088
spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notificationdb}
    username: ${DB_USER:resumeai}
    password: ${DB_PASS:resumeai}
  jpa:
    hibernate: { ddl-auto: validate }
    open-in-view: false
  flyway: { enabled: true, baseline-on-migrate: true }
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
